### PR TITLE
Fix: Make link unclickable. Closes #91

### LINKED ISSUE #91: [bug] Clicking a link in bterm
Reproduce: Type any link e.g. `http://google.com` in bterm window
bug: It opens up a webpage in new chromium window (without any close controls).

Fix:
Make a link un-clickable. Talked with Edis and agreed to make link un-clickable; That's the behaviour followed on OSX , Windows, Linux.
screen shot 2017-05-24 at 11 43 47 am

### PR DESCRIPTION
**Pull request by shumail92**
Closes #91

### CODE REVIEW

**Comment by marhi** [comment]
Not a very long term solution.

**Comment by irmana** [comment]
@marhi if it's not a long term, why do we merge then? I suggest we discuss this internally and see what do we want to achieve here.

**Comment by shumail92** [comment]
@marhi Can you suggest a better approach ?

I am working on writing the test at the moment.

**Comment by irmana** [comment]
@shumail92 we discussed this internally and I would propose the solution with configuration file where user can define which key combinations along with the mouse click make links clickable. How about that? So, by default links are not clickable, but if you press i.e. Ctrl + click then it opens up the link in a browser.

**Comment by shumail92** [comment]
@irmana Okay, I try for that. 
btw, I just updated my PR with test case for current behavior (un-clickable links).

**Comment by irmana** [comment]
@shumail92 please submit a solution in 2 separate commits... 1st commit with the fix, 2nd commit with the test/s

**Comment by shumail92** [comment]
@irmana Sure. When I submit solution for new proposed approach, I'll split into 2 commits. Thanks

**Comment by irmana** [comment]
@shumail92 please set the label in progress

**Comment by shumail92** [comment]
@irmana I don't have permissions to set labels.

**Comment by marhi** [comment]
What's the progress? I have the solution for opening the link in OS browser, it's just three lines?
Maybe a few lines to make it a config file option.

**Comment by jkuri** [comment]
i personally would prefer opening url in the browser.

-- 
Jan Kuri

**Comment by omerson** [comment]
I would add none of the well known terminals support this.

**Comment by jkuri** [comment]
@omerson whats your point? we are not copying iterm2 or something.

**Comment by marhi** [comment]
I agree with that, but isn't it our goal here to be innovative and offer something more than others?

**Comment by irmana** [comment]
What I would personally find intriguing is:
- By default if I click once it copies the link 
- When I press Ctrl and click then it opens the link in a browser

That would be fantastic I think.

**Comment by omerson** [comment]
@marhi I agree just refering to standards and user expectations.

**Comment by shumail92** [comment]
I added the behavior that @irmana suggested. For the tests, I added a basic test for asserting that link doesn't open on clicking a url(without pressing ctrl or cmd on mac) in bterm window. 
I will also try to add a check for asserting if link is copied.

File: src/app/components/window-terminal/window-terminal.component.ts [hunk 1]
```diff
@@ -50,6 +50,19 @@ export class WindowTerminalComponent implements OnInit {
         this.copy();
       }, 800);
     }, false);
+
+    document.addEventListener('click', function (e) {
```
Comment (jkuri) [inline src/app/components/window-terminal/window-terminal.component.ts]: use `@HostListener`.

File: src/app/components/window-terminal/window-terminal.component.ts [hunk 2]
```diff
@@ -50,6 +50,19 @@ export class WindowTerminalComponent implements OnInit {
...
+      if (e.target['tagName'] === 'A') {
+        e.preventDefault();
+        clipboard.writeText(e.target['href']);
+        let isMac = process.platform === 'darwin'
```
Comment (jkuri) [inline src/app/components/window-terminal/window-terminal.component.ts]: missing `;`

**Comment by shumail92** [comment]
I'm selecting the link using `this.app.client.click('.xterm-rows div:first-child a'))` and it's passing test on my macOS. But tests are failing on circleci/appveyor. 
Any idea please?

**Comment by marhi** [comment]
Yes, your tests are very fragile. The presumtion that the link will be in the first line is rarely met. Usually there is stuff like MOTD printed / Windows version, etc in the first few lines...

Try with:
      .then(() => this.app.client.pause(2000))
      .then(() => this.app.client.click('.terminal-instance a'))

**Comment by shumail92** [comment]
Thankyou. I assume that because i clear terminal before writing link. In
case, there's some existing text (windows version etc) shouldn't it be
cleared with the `clear`?

File: src/app/components/window-terminal/window-terminal.component.ts [hunk 3]
```diff
@@ -52,6 +52,19 @@ export class WindowTerminalComponent implements OnInit {
     }, false);
   }
 
+  @HostListener('click', ['$event']) handleURLClick(event) {
```
Comment (jkuri) [inline src/app/components/window-terminal/window-terminal.component.ts]: `(event: MouseEvent)` please be more specific.

File: src/app/components/window-terminal/window-terminal.component.ts [hunk 4]
```diff
@@ -52,6 +52,19 @@ export class WindowTerminalComponent implements OnInit {
...
+    if (event.target['tagName'] === 'A') {
```
Comment (jkuri) [inline src/app/components/window-terminal/window-terminal.component.ts]: please use dot notation.

File: src/app/components/window-terminal/window-terminal.component.ts (hunk 3 above)
Comment (shumail92) [inline src/app/components/window-terminal/window-terminal.component.ts]: @jkuri Thank you for the review. I initially used `event: Mouseevent` but to avoid `Property tagName doesn't exist on type EventTarget` i changed it to Event. 
Is it fine if i leave those warnings like this? 
Or another workaround I was thinking to cast it inline like `(event.target as any).href` or `(event.target as any).tagName`. 
What would yo suggest

Comment (jkuri) [inline src/app/components/window-terminal/window-terminal.component.ts]: did you try `handleURLClick(event: MouseEvent)`?

Comment (shumail92) [inline src/app/components/window-terminal/window-terminal.component.ts]: Yes, same warning.

Comment (jkuri) [inline src/app/components/window-terminal/window-terminal.component.ts]: okay, then just use `(event: any)` I think, it will be okay

Comment (shumail92) [inline src/app/components/window-terminal/window-terminal.component.ts]: Sure, thanks. Updating.

**Comment by jkuri** [comment]
can you rebase your PR please?

**Comment by shumail92** [comment]
@jkuri Thanks. Sure I rebase it, on it.

**Comment by jkuri** [comment]
thanks!
